# Generated by Django 4.2.2 on 2023-07-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
